//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetLabo_Dev.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/PlanningWebServ")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artisan", Namespace="http://schemas.datacontract.org/2004/07/PlanningWebServ")]
    [System.SerializableAttribute()]
    public partial class Artisan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodePostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SigleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idArtisanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodePostal {
            get {
                return this.CodePostalField;
            }
            set {
                if ((this.CodePostalField.Equals(value) != true)) {
                    this.CodePostalField = value;
                    this.RaisePropertyChanged("CodePostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sigle {
            get {
                return this.SigleField;
            }
            set {
                if ((object.ReferenceEquals(this.SigleField, value) != true)) {
                    this.SigleField = value;
                    this.RaisePropertyChanged("Sigle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idArtisan {
            get {
                return this.idArtisanField;
            }
            set {
                if ((this.idArtisanField.Equals(value) != true)) {
                    this.idArtisanField = value;
                    this.RaisePropertyChanged("idArtisan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/PlanningWebServ")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodePostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateDerniereFacturationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateEntreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SigleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idClientField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodePostal {
            get {
                return this.CodePostalField;
            }
            set {
                if ((this.CodePostalField.Equals(value) != true)) {
                    this.CodePostalField = value;
                    this.RaisePropertyChanged("CodePostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateDerniereFacturation {
            get {
                return this.DateDerniereFacturationField;
            }
            set {
                if ((object.ReferenceEquals(this.DateDerniereFacturationField, value) != true)) {
                    this.DateDerniereFacturationField = value;
                    this.RaisePropertyChanged("DateDerniereFacturation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateEntree {
            get {
                return this.DateEntreeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateEntreeField, value) != true)) {
                    this.DateEntreeField = value;
                    this.RaisePropertyChanged("DateEntree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pays {
            get {
                return this.PaysField;
            }
            set {
                if ((object.ReferenceEquals(this.PaysField, value) != true)) {
                    this.PaysField = value;
                    this.RaisePropertyChanged("Pays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sigle {
            get {
                return this.SigleField;
            }
            set {
                if ((object.ReferenceEquals(this.SigleField, value) != true)) {
                    this.SigleField = value;
                    this.RaisePropertyChanged("Sigle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((this.TelephoneField.Equals(value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idClient {
            get {
                return this.idClientField;
            }
            set {
                if ((this.idClientField.Equals(value) != true)) {
                    this.idClientField = value;
                    this.RaisePropertyChanged("idClient");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ProjetLabo_Dev.ServiceReference1.CompositeType GetDataUsingDataContract(ProjetLabo_Dev.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ProjetLabo_Dev.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ProjetLabo_Dev.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestConnection", ReplyAction="http://tempuri.org/IService1/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestConnection", ReplyAction="http://tempuri.org/IService1/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectArtisans", ReplyAction="http://tempuri.org/IService1/selectArtisansResponse")]
        ProjetLabo_Dev.ServiceReference1.Artisan[] selectArtisans();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectArtisans", ReplyAction="http://tempuri.org/IService1/selectArtisansResponse")]
        System.Threading.Tasks.Task<ProjetLabo_Dev.ServiceReference1.Artisan[]> selectArtisansAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ArtisanSelectByDetails", ReplyAction="http://tempuri.org/IService1/ArtisanSelectByDetailsResponse")]
        ProjetLabo_Dev.ServiceReference1.Artisan[] ArtisanSelectByDetails(ProjetLabo_Dev.ServiceReference1.Artisan artisanInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ArtisanSelectByDetails", ReplyAction="http://tempuri.org/IService1/ArtisanSelectByDetailsResponse")]
        System.Threading.Tasks.Task<ProjetLabo_Dev.ServiceReference1.Artisan[]> ArtisanSelectByDetailsAsync(ProjetLabo_Dev.ServiceReference1.Artisan artisanInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ArtisanAdd", ReplyAction="http://tempuri.org/IService1/ArtisanAddResponse")]
        void ArtisanAdd(ProjetLabo_Dev.ServiceReference1.Artisan artisan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ArtisanAdd", ReplyAction="http://tempuri.org/IService1/ArtisanAddResponse")]
        System.Threading.Tasks.Task ArtisanAddAsync(ProjetLabo_Dev.ServiceReference1.Artisan artisan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ArtisanRemove", ReplyAction="http://tempuri.org/IService1/ArtisanRemoveResponse")]
        void ArtisanRemove(ProjetLabo_Dev.ServiceReference1.Artisan idArtisan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ArtisanRemove", ReplyAction="http://tempuri.org/IService1/ArtisanRemoveResponse")]
        System.Threading.Tasks.Task ArtisanRemoveAsync(ProjetLabo_Dev.ServiceReference1.Artisan idArtisan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllClients", ReplyAction="http://tempuri.org/IService1/SelectAllClientsResponse")]
        ProjetLabo_Dev.ServiceReference1.Client[] SelectAllClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllClients", ReplyAction="http://tempuri.org/IService1/SelectAllClientsResponse")]
        System.Threading.Tasks.Task<ProjetLabo_Dev.ServiceReference1.Client[]> SelectAllClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientSelectByDetails", ReplyAction="http://tempuri.org/IService1/ClientSelectByDetailsResponse")]
        ProjetLabo_Dev.ServiceReference1.Client[] ClientSelectByDetails(ProjetLabo_Dev.ServiceReference1.Client artisanInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientSelectByDetails", ReplyAction="http://tempuri.org/IService1/ClientSelectByDetailsResponse")]
        System.Threading.Tasks.Task<ProjetLabo_Dev.ServiceReference1.Client[]> ClientSelectByDetailsAsync(ProjetLabo_Dev.ServiceReference1.Client artisanInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientAdd", ReplyAction="http://tempuri.org/IService1/ClientAddResponse")]
        void ClientAdd(ProjetLabo_Dev.ServiceReference1.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientAdd", ReplyAction="http://tempuri.org/IService1/ClientAddResponse")]
        System.Threading.Tasks.Task ClientAddAsync(ProjetLabo_Dev.ServiceReference1.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientRemove", ReplyAction="http://tempuri.org/IService1/ClientRemoveResponse")]
        void ClientRemove(ProjetLabo_Dev.ServiceReference1.Client idClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientRemove", ReplyAction="http://tempuri.org/IService1/ClientRemoveResponse")]
        System.Threading.Tasks.Task ClientRemoveAsync(ProjetLabo_Dev.ServiceReference1.Client idClient);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProjetLabo_Dev.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProjetLabo_Dev.ServiceReference1.IService1>, ProjetLabo_Dev.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ProjetLabo_Dev.ServiceReference1.CompositeType GetDataUsingDataContract(ProjetLabo_Dev.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ProjetLabo_Dev.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ProjetLabo_Dev.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        public ProjetLabo_Dev.ServiceReference1.Artisan[] selectArtisans() {
            return base.Channel.selectArtisans();
        }
        
        public System.Threading.Tasks.Task<ProjetLabo_Dev.ServiceReference1.Artisan[]> selectArtisansAsync() {
            return base.Channel.selectArtisansAsync();
        }
        
        public ProjetLabo_Dev.ServiceReference1.Artisan[] ArtisanSelectByDetails(ProjetLabo_Dev.ServiceReference1.Artisan artisanInfo) {
            return base.Channel.ArtisanSelectByDetails(artisanInfo);
        }
        
        public System.Threading.Tasks.Task<ProjetLabo_Dev.ServiceReference1.Artisan[]> ArtisanSelectByDetailsAsync(ProjetLabo_Dev.ServiceReference1.Artisan artisanInfo) {
            return base.Channel.ArtisanSelectByDetailsAsync(artisanInfo);
        }
        
        public void ArtisanAdd(ProjetLabo_Dev.ServiceReference1.Artisan artisan) {
            base.Channel.ArtisanAdd(artisan);
        }
        
        public System.Threading.Tasks.Task ArtisanAddAsync(ProjetLabo_Dev.ServiceReference1.Artisan artisan) {
            return base.Channel.ArtisanAddAsync(artisan);
        }
        
        public void ArtisanRemove(ProjetLabo_Dev.ServiceReference1.Artisan idArtisan) {
            base.Channel.ArtisanRemove(idArtisan);
        }
        
        public System.Threading.Tasks.Task ArtisanRemoveAsync(ProjetLabo_Dev.ServiceReference1.Artisan idArtisan) {
            return base.Channel.ArtisanRemoveAsync(idArtisan);
        }
        
        public ProjetLabo_Dev.ServiceReference1.Client[] SelectAllClients() {
            return base.Channel.SelectAllClients();
        }
        
        public System.Threading.Tasks.Task<ProjetLabo_Dev.ServiceReference1.Client[]> SelectAllClientsAsync() {
            return base.Channel.SelectAllClientsAsync();
        }
        
        public ProjetLabo_Dev.ServiceReference1.Client[] ClientSelectByDetails(ProjetLabo_Dev.ServiceReference1.Client artisanInfo) {
            return base.Channel.ClientSelectByDetails(artisanInfo);
        }
        
        public System.Threading.Tasks.Task<ProjetLabo_Dev.ServiceReference1.Client[]> ClientSelectByDetailsAsync(ProjetLabo_Dev.ServiceReference1.Client artisanInfo) {
            return base.Channel.ClientSelectByDetailsAsync(artisanInfo);
        }
        
        public void ClientAdd(ProjetLabo_Dev.ServiceReference1.Client client) {
            base.Channel.ClientAdd(client);
        }
        
        public System.Threading.Tasks.Task ClientAddAsync(ProjetLabo_Dev.ServiceReference1.Client client) {
            return base.Channel.ClientAddAsync(client);
        }
        
        public void ClientRemove(ProjetLabo_Dev.ServiceReference1.Client idClient) {
            base.Channel.ClientRemove(idClient);
        }
        
        public System.Threading.Tasks.Task ClientRemoveAsync(ProjetLabo_Dev.ServiceReference1.Client idClient) {
            return base.Channel.ClientRemoveAsync(idClient);
        }
    }
}
